#!/usr/bin/env python3
from datetime import datetime

glds_num = "121"

with open(f"iDEP_GLDS{glds_num}.Rmd", "a") as result:
    with open("iDEP_R_Markdown.Rmd", "r") as mkdwn:
        for line in mkdwn:
            if line.startswith("title:"):
                print(line)
                result.write("title: 'GLDS-{} Analysis Using iDEP 0.91'\n".format(glds_num))
            
            elif line.startswith("author:"):
                result.write("author: Hyun-seok 'Ren' Chang \n")
            
            elif line.startswith("date:"):
                result.write("date: " + datetime.now().strftime("%c") + "\n")
            
            elif line.startswith(" This R markdown file was auto-generated by the"):
                result.write(f"""Analysis of [GLDS-{glds_num}](https://genelab-data.ndc.nasa.gov/genelab/accession/GLDS-{glds_num}/) from NASA GeneLab \n
This R markdown file was auto-generated by the [iDEP website](http://ge-lab.org/idep/)
Using iDEP 0.91, originally by Steven Xijin.Ge@sdstate.edu \n
Ge SX, Son EW, Yao R: iDEP: an integrated web application for differential expression and pathway analysis of RNA-Seq data. BMC Bioinformatics 2018, 19(1):534. PMID:30567491""")

            elif line.startswith(" setwd("):
                result.write(f" setwd('~/Documents/HTML_R/GLDS{glds_num}')\n")

            elif line.startswith(" inputFile <- "):
                result.write(f" inputFile <- 'GLDS{glds_num}_Expression.csv'\n")

            elif line.startswith(" sampleInfoFile <-"):
                result.write(f" sampleInfoFile <- 'GLDS{glds_num}_Sampleinfo.csv'\n gldsMetadataFile <- 'GLDS{glds_num}_Metadata.csv'\n")

            elif line.startswith(" readData.out <- readData(inputFile)"):
                result.write("""readMetadata.out <- readMetadata(gldsMetadataFile)
library(knitr)   #  install if needed. for showing tables with kable
library(kableExtra)
kable( readMetadata.out ) %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  scroll_box(width = "100%")
```

```{r, message=FALSE  }  
 readData.out <- readData(inputFile) 
  
  """)
            elif line.startswith(" library(knitr)"):
                pass

            elif line.startswith(" kable("):
                result.write(line.split("#", 1)[0].rstrip() + """ %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  scroll_box(width = "100%") \n""")

            elif line.startswith(" ix = grep('Mus musculus', "):
                 result.write(" ix = grep('Arabidopsis thaliana', STRING10_species$official_name ) \n")

            elif line.startswith("```{r, message=FALSE  }"):
                result.write("```{r, message=FALSE, error=TRUE  }\n")
            else:
                result.write(line)
